routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
    // return view('welcome');
// });

/** Frontend Routes */
Route::get('/', 'FrontendController@index')->name('homepage');
Route::get('/search', 'CompanyController@getSearchResult')->name('search');
Route::get('/help-and-faq',function(){
    return view('home.faq');
})->name('help-faq');

Route::get('/about-us', function(){
    return view('home.about-us');
})->name('about-us');

Route::get('/contact-us', function(){
    return view('home.contact');
})->name('contact-us');

/** Frontend Routes closes */

Auth::routes();
Route::get('/userprofile', 'UserController@compUser')->name('compuser');
Route::get('/userprofileedit', 'UserController@compUserEdit')->name('compuseredit');
Route::get('/userprofiledel', 'UserController@compUserDel')->name('compuserdel');
Route::get('/register',function(){
    return view('home.register');
})->name('register');

Route::post('/register','UserController@registerUser')->name('register-user');
Route::get('/active/{token}','UserController@activateUser')->name('activate-user');

// Route::get('/register',function(){
//     return redirect()->route('login');
// });


/** Backend Routes */
Route::group(['middleware'=>'auth'],  function(){
    Route::group(['prefix'=>'admin', 'middleware' => 'admin'], function(){
        Route::get('/', 'HomeController@admin')->name('admin');
        Route::resource('company' ,'CompanyController');
        Route::resource('user' ,'UserController');
        Route::resource('banner' ,'BannerController');

        Route::get('/profile','UserController@adminProfile')->name('admin-profile');
        Route::put('/profile/{id}', 'UserController@updateAdmin')->name('admin-update');
        

    });


    Route::group(['prefix'=>'company', 'middleware' => 'company'], function(){
        Route::get('/', 'HomeController@company')->name('company');
        Route::resource('employee' ,'EmployeeController');
    });


    Route::group(['prefix'=>'user', 'middleware' => 'user'], function(){
        Route::get('/', 'HomeController@user')->name('user');
        Route::resource('profileuser' ,'UserFrontController');
    });

});

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/section/copyright.blade.php
<footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Company {{ date('Y') }}</span>
          </div>
        </div>
      </footer>

resources/views/admin/section/footer.blade.php
</html>

resources/views/admin/section/header.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

    <!-- Custom fonts for this template-->
    <link href="{{ asset('assets/admin/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    @yield('datataleslinks')
    <!-- Custom styles for this template-->
    <link href="{{ asset('assets/admin/css/sb-admin-2.min.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/admin/css/gijgo.min.css') }}" rel="stylesheet">

</head>

resources/views/admin/section/logout.blade.php
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="{{ route('logout') }}" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                    Logout
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/section/notification.blade.php
@if(session()->has('success'))
<p class="alert alert-success">{{ session('success') }}</p>
@endif
@if(session()->has('error'))
<p class="alert alert-error">{{ session('error') }}</p>
@endif
<script>
    setTimeout(function(){
        $('.alert').slideUp();
    }, 3000);
</script>

resources/views/admin/section/scripts.blade.php
<script src="{{ asset('assets/admin/vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ asset('assets/admin/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{ asset('assets/admin/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{{ asset('assets/admin/js/sb-admin-2.min.js') }}"></script>
  <script src="{{ asset('assets/admin/js/gijgo.min.js') }}"></script>
  @yield('datatablesscripts')

</body>

resources/views/admin/section/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ route('home') }}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-users-cog"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Welcome {{ Auth::user()->name }}</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="{{ route('home')}}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>DASHBOARD</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{{ route('banner.index') }}">
          <i class="fas fa-sitemap"></i>
          <span>Banner Management</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{{ route('company.index') }}">
          <i class="fas fa-sitemap"></i>
          <span>Company Management</span></a>
      </li>


      <li class="nav-item">
        <a class="nav-link" href="{{ route('user.index') }}">
          <i class="fas fa-users"></i>
          <span>User Management</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{{ route('admin-profile') }}">
          <i class="fas fa-user"></i>
          <span>Change Profile</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>

resources/views/admin/section/top-nav.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>
        <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->name }}</span>
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{{ route('admin-profile') }}">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>