routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
    // return view('welcome');
// });

/** Frontend Routes */
Route::get('/', 'FrontendController@index')->name('homepage');
Route::get('/search', 'CompanyController@getSearchResult')->name('search');
Route::get('/help-and-faq',function(){
    return view('home.faq');
})->name('help-faq');

Route::get('/about-us', function(){
    return view('home.about-us');
})->name('about-us');

Route::get('/contact-us', function(){
    return view('home.contact');
})->name('contact-us');

/** Frontend Routes closes */

Auth::routes();
Route::get('/userprofile', 'UserController@compUser')->name('compuser');
Route::get('/userprofileedit', 'UserController@compUserEdit')->name('compuseredit');
Route::get('/userprofiledel', 'UserController@compUserDel')->name('compuserdel');
Route::get('/register',function(){
    return view('home.register');
})->name('register');

Route::post('/register','UserController@registerUser')->name('register-user');
Route::get('/active/{token}','UserController@activateUser')->name('activate-user');

// Route::get('/register',function(){
//     return redirect()->route('login');
// });


/** Backend Routes */
Route::group(['middleware'=>'auth'],  function(){
    Route::group(['prefix'=>'admin', 'middleware' => 'admin'], function(){
        Route::get('/', 'HomeController@admin')->name('admin');
        Route::resource('company' ,'CompanyController');
        Route::resource('user' ,'UserController');
        Route::resource('banner' ,'BannerController');

        Route::get('/profile','UserController@adminProfile')->name('admin-profile');
        Route::put('/profile/{id}', 'UserController@updateAdmin')->name('admin-update');
        

    });


    Route::group(['prefix'=>'company', 'middleware' => 'company'], function(){
        Route::get('/', 'HomeController@company')->name('company');
        Route::resource('employee' ,'EmployeeController');
    });


    Route::group(['prefix'=>'user', 'middleware' => 'user'], function(){
        Route::get('/', 'HomeController@user')->name('user');
        Route::resource('profileuser' ,'UserFrontController');
    });

});

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = ['added_by','name', 'summary', 'description', 'address', 'role', 'image', 'status'];

    public function getRules()
    {
        return [
            'name' => 'nullable|string',
            'image' => 'sometimes|image|max:5000',
            'summary' => 'nullable|string',
            'address' => 'nullable|string',
            'description' => 'nullable|string',
            'role' => 'required|in:manager,receptionist,operator',
            'status' => 'required|in:active,inactive',
        ];
    }

}

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = ['added_by','name', 'skills', 'description', 'address','phone', 'role', 'image', 'status'];

    public function getRules()
    {
        return [
            'name' => 'nullable|string',
            'image' => 'sometimes|image|max:5000',
            'skills' => 'nullable|string',
            'address' => 'nullable|string',
            'phone' => 'nullable|string',
            'description' => 'nullable|string',
            'role' => 'required|in:manager,receptionist,operator',
            'status' => 'required|in:active,inactive',
        ];
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;
use App\Models\Company;

use Illuminate\Http\Request;

class CompanyController extends Controller
{
    protected $company = null;

    public function __construct(Company $company)
    {
        $this->company = $company;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->company = $this->company->get();
        return view('admin.company.index')->with('company_data', $this->company); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.company.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules= $this->company->getRules(); //validation//   //$rules = $company->getRules(); from models
       $request->validate($rules);
       //dd($request);

       $data= $request->all();   //all(); receive all data inserted from form
       $data['added_by'] = $request->user()->id; //to check whether data is added by admin or user by id

        //dd($request);
        if($request->image){
            $file_name =  uploadImage($request->image, "companies");    //uploadImage is autoloading function from helpers.php
            if($file_name){
                $data['image'] = $file_name;
            } else {
                $data['image'] =null;
            }
        }
        $this->company->fill($data);
        $success = $this->company->save();
        if($success){
            $request->session()->flash('success','company added successfully.');
        } else {
            $request->session()->flash('error','Problem while adding company.');
        }
        //dd($data);

        return redirect()->route('company.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $this->company =$this->company->find($id); // SELECT * FROM company WHERE id = $id //find function from form
        if(!$this->company){
            request()->session()->flash('error','Company not found');
            return redirect()->route('company.index');
        }

        return view('admin.company.form')->with('company',$this->company);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules= $this->company->getRules(); //validation//   //$rules = $company->getRules(); from models
       $request->validate($rules);
       //dd($request);

       $data= $request->all();   //all(); receive all data inserted from form
       $this->company = $this->company->find($id);

        //dd($request);
        if($request->image){
            $file_name =  uploadImage($request->image, "companies");    //uploadImage is autoloading function from helpers.php
            if($file_name){
                $data['image'] = $file_name;
            } else {
                $data['image'] =null;
            }
        }
        $this->company->fill($data);
        $success = $this->company->save();
        if($success){
            $request->session()->flash('success','company updated successfully.');
        } else {
            $request->session()->flash('error','Problem while updating company.');
        }
        //dd($data);

        return redirect()->route('company.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->company = $this->company->find($id);   // SELECT * FROM company WHERE id = $id //find function is used to find specic data from form
        if(!$this->company){
            request()->session()->flash('error','Company not found');
            return redirect()->route('company.index');
        }

        $image = $this->company->image;  //store into $image
        $del = $this->company->delete();    //delete image from database using delete function 
        if($del){
            // image
            if(!empty($image) && file_exists(public_path().'/uploads/companies/'.$image)){
                unlink(public_path().'/uploads/companies/'.$image);
            }
            request()->session()->flash('success','Company Deleted successfully');
        } else {
            request()->session()->flash('error','Problem while deleting company');
        }
        return redirect()->route('company.index');  //return to index page
    }

    public function getSearchResult(Request $request){
        // SELECT * FROM companies WHERE status = 'active' AND (name  LIKE '%'.$request->search.'%' OR summary LIKE '%'.$request->search.'%')
        // %test%
        $this->company = $this->company->where('status','active')
                                        ->where(function($query){
                                            global $request;
                                            return $query->Where(
                                                'name','LIKE','%'.$request->search.'%')
                                                ->orWhere('summary', 'LIKE', '%'.$request->search.'%')
                                                ->orWhere('description', 'LIKE', '%'.$request->search.'%');
                                        })->paginate(24);
        return view('home.company-list')->with('companies',$this->company);
    }

}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;
use App\Models\Employee;

use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    protected $employee = null;

    public function __construct(Employee $employee)
    {
        $this->employee = $employee;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $this->employee =$this->employee->get();
        return view('company.employee.index')->with('employee_data',$this->employee); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('company.employee.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules= $this->employee->getRules(); //validation//   //$rules = $company->getRules(); from models
       $request->validate($rules);
       //dd($request);

       $data= $request->all();   //all(); receive all data inserted from form
       $data['added_by'] = $request->user()->id; //to check whether data is added by admin or user by id

        //dd($request);
        if($request->image){
            $file_name =  uploadImage($request->image, "employees");    //uploadImage is autoloading function from helpers.php
            if($file_name){
                $data['image'] = $file_name;
            } else {
                $data['image'] =null;
            }
        }
        $this->employee->fill($data);
        $success = $this->employee->save();
        if($success){
            $request->session()->flash('success','employee added successfully.');
        } else {
            $request->session()->flash('error','Problem while adding employee.');
        }
        //dd($data);

        return redirect()->route('employee.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->employee =$this->employee->find($id); // SELECT * FROM company WHERE id = $id //find function from form
        if(!$this->employee){
            request()->session()->flash('error','employee not found');
            return redirect()->route('employee.index');
        }

        return view('company.employee.form')->with('employee',$this->employee);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules= $this->employee->getRules(); //validation//   //$rules = $company->getRules(); from models
        $request->validate($rules);
        //dd($request);
 
        $data= $request->all();   //all(); receive all data inserted from form
        $this->employee = $this->employee->find($id);
 
         //dd($request);
         if($request->image){
             $file_name =  uploadImage($request->image, "employees");    //uploadImage is autoloading function from helpers.php
             if($file_name){
                 $data['image'] = $file_name;
             } else {
                 $data['image'] =null;
             }
         }
         $this->employee->fill($data);
         $success = $this->employee->save();
         if($success){
             $request->session()->flash('success','employee updated successfully.');
         } else {
             $request->session()->flash('error','Problem while updating employee.');
         }
         //dd($data);
 
         return redirect()->route('employee.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->employee = $this->employee->find($id);   // SELECT * FROM company WHERE id = $id //find function is used to find specic data from form
        if(!$this->employee){
            request()->session()->flash('error','Employees not found');
            return redirect()->route('employee.index');
        }

        $image = $this->employee->image;  //store into $image
        $del = $this->employee->delete();    //delete image from database using delete function 
        if($del){
            // image
            if(!empty($image) && file_exists(public_path().'/uploads/employees/'.$image)){
                unlink(public_path().'/uploads/employees/'.$image);
            }
            request()->session()->flash('success','employee Deleted successfully');
        } else {
            request()->session()->flash('error','Problem while deleting employee');
        }
        return redirect()->route('employee.index');  //return to index page
    }
}

resources/views/company/employee/form.blade.php
@extends('layouts.company-dashboard')
@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">employee {{ (isset($employee) && $employee->count()) > 0 ? 'Update' : 'Add' }} </h1>
    <div class="row">

        <div class="col-12">
            @if(isset($employee) )
            {{ Form::open(['url'=>route('employee.update', $employee->id), 'class'=>'form', 'enctype'=>'multipart/form-data']) }}
            @method('PUT')
            @else
            {{ Form::open(['url' =>route('employee.store'), 'class'=>'Form', 'enctype' =>'multipart/form-data']) }}
            @endif
            <div class="form-group row">
                {{ Form::label('name', 'Name: ', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                    {{ Form::text('name', @$employee->name, ['class'=>'form-control form-control-sm', 'id'=>'name']) }}
                    @if($errors->has('name'))
                    <span class="alert-danger">{{ $errors->first('name') }}</span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                {{ Form::label('skills','Employee: ',['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                    {{Form::textarea('skills', @$employee->skills,['class'=>'form-control','id'=>'skills']) }}
                    @if($errors->has('skills'))
                    <span class="alert-danger">
                        {{ $errors->first('skills') }}
                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                {{ Form::label('description','Description: ', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                    {{ Form::textarea('description',  @$employee->description, ['class'=>'form-control','rows'=>5, 'style'=>'resize:none', 'id'=>'description']) }}
                    @if($errors->has('description'))
                    <span class="alert-danger">{{ $errors->first('description') }}</span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                {{ Form::label('address','Address: ',['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                    {{Form::textarea('address', @$employee->address,['class'=>'form-control','id'=>'address']) }}
                    @if($errors->has('address'))
                    <span class="alert-danger">
                        {{ $errors->first('address') }}
                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                {{ Form::label('role', 'Role: ', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                    {{ Form::select('role',['manager'=> 'Manager','receptionist'=>'Receptionist','operator'=>'Operator'], @$employee->role, ['class'=>'form-control form-control-sm', 'id'=>'role', 'required'=>true]) }}
                    @if($errors->has('role'))
                    <span class="alert-danger">{{ $errors->first('role') }}</span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                {{ Form::label('status', 'Status: ', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                    {{ Form::select('status',['active'=> 'Active','inactive'=>'Inactive'], @$employee->status, ['class'=>'form-control form-control-sm', 'id'=>'status', 'required'=>true]) }}
                    @if($errors->has('status'))
                    <span class="alert-danger">{{ $errors->first('status') }}</span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                {{ Form::label('phone','Phone: ', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                    {{ Form::tel('phone', @$employee->phone, ['class'=>'form-control', 'id'=>'phone']) }}
                    @if($errors->has('phone'))
                    <span class="alert-danger">{{ $errors->first('phone') }}</span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                {{ Form::label('image', 'Image: ', ['class'=>'col-sm-3']) }}
                <div class="col-sm-4">
                    {{ Form::file('image', ['id'=>'image', 'required'=> (isset($employee)) ? false : true, 'accept'=>'image/*']) }}
                    @if($errors->has('image'))
                    <span class="alert-danger">{{ $errors->first('image') }}</span>
                    @endif
                </div>

                @if(isset($employee) && file_exists(public_path().'/uploads/companies/'.$employee->image))
                <div class="col-sm-4">
                    <img src="{{ asset('uploads/companies/'.$employee->image) }}" alt="" class="img img-responsive img-thumbnail">
                </div>
                @endif
            </div>

            <div class="form-group row">
                {{ Form::label('','', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                    {{ Form::button('<i class="fas fa-paper-plane"></i> Submit', ['id'=>'submit', 'class'=> 'btn btn-success', 'type'=>'submit']) }}
                    {{ Form::button('<i class="fas fa-trash"></i> Cancel', ['id'=>'cancel', 'class'=> 'btn btn-danger', 'type'=>'reset']) }}
                </div>
            </div>


        </div>
    </div>
    {{ Form::close() }}
</div>
@endsection
@section('scripts')
<script src="{{ asset('assets/admin/plugins/ckeditor/ckeditor.js') }}"></script>
<script>
    ClassicEditor.create(document.querySelector('#description'));
    $('#datepicker').datepicker();
</script>
@endsection

resources/views/company/employee/index.blade.php
@extends('layouts.company-dashboard')

@section('title')
Employee List || Company, Company
@endsection
@section('datataleslinks')
<link rel="stylesheet" href="{{ asset('assets/admin/css/jquery.dataTables.min.css') }}">
@endsection
@section('datatablesscripts')
<script src="{{ asset('assets/admin/js/jquery.dataTables.min.js') }}"></script>
<script>
    $('.table').dataTable();
</script>
@endsection


@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Employee List
        <a href="{{ route('employee.create') }}" class="btn btn-success float-right">
            <i class="fas fa-fw fa-plus"></i>
            Add Employee
        </a>
    </h1>
    @include('admin.section.notification')
    <table class="table">
        <thead>
            <th>S.N </th>
            <th>Name</th>
            <th>Image</th>
            <th>Role</th>
            <th>Status</th>
            <th>Action</th>
        </thead>
        <tbody>
        @if($employee_data)
            @foreach($employee_data as $key=>$value)
            <tr>
                <td> {{ $key+1 }}</td>
                <td>{{ $value->name}}</td>
                <td>
                    @if($value->image !=null && file_exists(public_path().'/uploads/employees/'.$value->image))
                    <img style="max-width: 150px;" src="{{ asset('uploads/employees/'.$value->image) }}" alt="" class="img img-responsive img-thumbnail">
                    @endif
                </td>
                <td>{{ ucfirst($value->role) }}</td>
                <td>{{ ucfirst($value->status) }}</td>

                <td> <a href="{{ route('employee.edit', $value->id) }}" style="border-radius: 50%" class="btn btn-success">
                        <i class="fas fa-pencil-alt"></i>
                    </a>

                    <form onsubmit="return confirm('Are you sure you want to delete this employee?')" action="{{ route('employee.destroy', $value->id) }}" method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" style="border-radius: 50%">
                            <i class="fas fa-trash"></i>
                        </button>
                    </form>
                </td>
            </tr>
            @endforeach
            @endif
        </tbody>
        </tbody>
    </table>

</div>
        

@endsection