routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
    // return view('welcome');
// });

/** Frontend Routes */
Route::get('/', 'FrontendController@index')->name('homepage');
Route::get('/search', 'CompanyController@getSearchResult')->name('search');
Route::get('/help-and-faq',function(){
    return view('home.faq');
})->name('help-faq');

Route::get('/about-us', function(){
    return view('home.about-us');
})->name('about-us');

Route::get('/contact-us', function(){
    return view('home.contact');
})->name('contact-us');

/** Frontend Routes closes */

Auth::routes();
Route::get('/userprofile', 'UserController@compUser')->name('compuser');
Route::get('/userprofileedit', 'UserController@compUserEdit')->name('compuseredit');
Route::get('/userprofiledel', 'UserController@compUserDel')->name('compuserdel');
Route::get('/register',function(){
    return view('home.register');
})->name('register');

Route::post('/register','UserController@registerUser')->name('register-user');
Route::get('/active/{token}','UserController@activateUser')->name('activate-user');

// Route::get('/register',function(){
//     return redirect()->route('login');
// });


/** Backend Routes */
Route::group(['middleware'=>'auth'],  function(){
    Route::group(['prefix'=>'admin', 'middleware' => 'admin'], function(){
        Route::get('/', 'HomeController@admin')->name('admin');
        Route::resource('company' ,'CompanyController');
        Route::resource('user' ,'UserController');
        Route::resource('banner' ,'BannerController');

        Route::get('/profile','UserController@adminProfile')->name('admin-profile');
        Route::put('/profile/{id}', 'UserController@updateAdmin')->name('admin-update');
        

    });


    Route::group(['prefix'=>'company', 'middleware' => 'company'], function(){
        Route::get('/', 'HomeController@company')->name('company');
        Route::resource('employee' ,'EmployeeController');
    });


    Route::group(['prefix'=>'user', 'middleware' => 'user'], function(){
        Route::get('/', 'HomeController@user')->name('user');
        Route::resource('profileuser' ,'UserFrontController');
    });

});

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Banner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Banner extends Model
{

    protected $fillable = ['title','link','status', 'image', 'added_by'];

    public function getRules($option='add'){
        return [
            'title' => 'required|string',
            'link' => 'nullable|url',
            'status' => 'required|in:active,inactive',
            'image' => (($option == 'add') ? 'required' : 'sometimes').'|image|max:5000|dimensions:min_width=1900'

        ];
    }
}

app/Http/Controllers/BannerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Banner;
use Illuminate\Http\Request;

class BannerController extends Controller
{
    protected $banner = null;

    public function __construct(Banner $banner)
    {
        $this->banner = $banner;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $this->banner = $this->banner->get();   // SELECT * FROM banners

        return view('admin.banner.index')
            ->with('banner_data', $this->banner);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.banner.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = $this->banner->getRules();
        $request->validate($rules);

        $data = $request->all();
        $data['added_by'] = $request->user()->id;

        if($request->image){
            $file_name = uploadImage($request->image, "banners");
            if($file_name){
                $data['image'] = $file_name;
            } else {
                $data['image'] = null;
            }
        }

        $this->banner->fill($data);
        $success = $this->banner->save();
        if($success){
            $request->session()->flash('success','Banner added successfully.');
        } else {
            $request->session()->flash('error','Problem while adding banner.');
        }
        return redirect()->route('banner.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->banner = $this->banner->find($id);
        if(!$this->banner){
            request()->session()->flash('error','Banner not found');
            return redirect()->route('banner.index');
        }

        return view('admin.banner.form')->with('banner', $this->banner);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = $this->banner->getRules('update');
        $request->validate($rules);

        $data = $request->all();
        $this->banner = $this->banner->find($id);

        if($request->image){
            $file_name = uploadImage($request->image, "banners");
            if($file_name){
                $data['image'] = $file_name;

                if(file_exists(public_path().'/uploads/banners/'.$this->banner->image)){
                    unlink(public_path().'/uploads/banners/'.$this->banner->image);
                }
            }
        }

        $this->banner->fill($data);
        $success = $this->banner->save();
        if($success){
            $request->session()->flash('success','Banner updated successfully.');
        } else {
            $request->session()->flash('error','Problem while updating banner.');
        }
        return redirect()->route('banner.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->banner = $this->banner->find($id);   // SELECT * FROM banners WHERE id = $id
        if(!$this->banner){
            request()->session()->flash('error','Banner not found');
            return redirect()->route('banner.index');
        }

        $image = $this->banner->image;
        $del = $this->banner->delete();
        if($del){
            // image
            if(!empty($image) && file_exists(public_path().'/uploads/banners/'.$image)){
                unlink(public_path().'/uploads/banners/'.$image);
            }
            request()->session()->flash('success','Banner Deleted successfully');
        }else {
            request()->session()->flash('error','Problem while deleting banner');
        }
        return redirect()->route('banner.index');
    }
}

resources/views/admin/banner/form.blade.php
@extends('layouts.admin-dashboard')
@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Banner {{ (isset($banner) && $banner->count()) > 0 ? 'Update' : 'Add' }} </h1>
    <div class="row">

    <div class="col-12">
            @if(isset($banner) )
            {{ Form::open(['url'=>route('banner.update', $banner->id), 'class'=>'form', 'enctype'=>'multipart/form-data']) }}
            @method('PUT')
            @else
            {{ Form::open(['url' =>route('banner.store'), 'class'=>'Form', 'enctype' =>'multipart/form-data']) }}
            @endif
            <div class="form-group row">
                {{ Form::label('title', 'Title: ', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                    {{ Form::text('title', @$banner->title, ['class'=>'form-control form-control-sm', 'id'=>'title']) }}
                    @if($errors->has('title'))
                    <span class="alert-danger">{{ $errors->first('title') }}</span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                {{ Form::label('link', 'Link: ', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                    {{ Form::url('link', @$banner->link, ['class'=>'form-control form-control-sm', 'id'=>'url']) }}
                    @if($errors->has('url'))
                    <span class="alert-danger">{{ $errors->first('url') }}</span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                {{ Form::label('status', 'Status: ', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                    {{ Form::select('status',['active'=> 'Active','inactive'=>'Inactive'], @$banner->status, ['class'=>'form-control form-control-sm', 'id'=>'status', 'required'=>true]) }}
                    @if($errors->has('status'))
                    <span class="alert-danger">{{ $errors->first('status') }}</span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                {{ Form::label('image', 'Image: ', ['class'=>'col-sm-3']) }}
                <div class="col-sm-4">
                    {{ Form::file('image', ['id'=>'image', 'required'=> (isset($banner)) ? false : true, 'accept'=>'image/*']) }}
                    @if($errors->has('image'))
                    <span class="alert-danger">{{ $errors->first('image') }}</span>
                    @endif
                </div>

                @if(isset($banner) && file_exists(public_path().'/uploads/banners/'.$banner->image))
                <div class="col-sm-4">
                    <img src="{{ asset('uploads/banners/'.$banner->image) }}" alt="" class="img img-responsive img-thumbnail">
                </div>
                @endif
            </div>

            <div class="form-group row">
                {{ Form::label('submit','', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                    {{ Form::button('<i class="fas fa-paper-plane"></i> Submit', ['id'=>'submit', 'class'=> 'btn btn-success', 'type'=>'submit']) }}
                    {{ Form::button('<i class="fas fa-trash"></i> Cancel', ['id'=>'cancel', 'class'=> 'btn btn-danger', 'type'=>'reset']) }}
                </div>
            </div>


        </div>
    </div>
    {{ Form::close() }}
</div>
@endsection
@section('scripts')
<script src="{{ asset('assets/admin/plugins/ckeditor/ckeditor.js') }}"></script>
<script>
    ClassicEditor.create(document.querySelector('#description'));
    $('#datepicker').datepicker();
</script>
@endsection

resources/views/admin/banner/index.blade.php
@extends('layouts.admin-dashboard')

@section('title')
Company List || Admin, EduTraining
@endsection
@section('datataleslinks')
<link rel="stylesheet" href="{{ asset('assets/admin/css/jquery.dataTables.min.css') }}">
@endsection
@section('datatablesscripts')
<script src="{{ asset('assets/admin/js/jquery.dataTables.min.js') }}"></script>
<script>
    $('.table').dataTable();
</script>
@endsection


@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Banner List
        <a href="{{ route('banner.create') }}" class="btn btn-success float-right">
            <i class="fas fa-fw fa-plus"></i>
            Add Banner
        </a>
    </h1>
    @include('admin.section.notification')
    <table class="table">
        <thead>
            <th>S.N </th>
            <th>Title</th>
            <th>Image</th>
            <th>Link</th>
            <th>Status</th>
            <th>Action</th>
        </thead>
        <tbody>
            @if($banner_data)
            @foreach($banner_data as $key=>$value)
            <tr>
                <td> {{ $key+1 }}</td>
                <td>{{ $value->title}}</td>
                <td>
                    @if($value->image !=null && file_exists(public_path().'/uploads/banners/'.$value->image))
                    <img style="max-width: 150px;" src="{{ asset('uploads/banners/'.$value->image) }}" alt="" class="img img-responsive img-thumbnail">
                    @endif
                </td>
                <td><a href="{{ $value->link}}" target="_link" class="btn btn-link">{{ $value->link}}</a></td>
                <td>{{ ucfirst($value->status) }}</td>

                <td> <a href="{{ route('banner.edit', $value->id) }}" style="border-radius: 50%" class="btn btn-success">
                        <i class="fas fa-pencil-alt"></i>
                    </a>

                    <form onsubmit="return confirm('Are you sure you want to delete this banner?')" action="{{ route('banner.destroy', $value->id) }}" method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" style="border-radius: 50%">
                            <i class="fas fa-trash"></i>
                        </button>
                    </form>
                </td>
            </tr>
            @endforeach
            @endif
        </tbody>
    </table>

</div>


@endsection