routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
    // return view('welcome');
// });

/** Frontend Routes */
Route::get('/', 'FrontendController@index')->name('homepage');
Route::get('/search', 'CompanyController@getSearchResult')->name('search');
Route::get('/help-and-faq',function(){
    return view('home.faq');
})->name('help-faq');

Route::get('/about-us', function(){
    return view('home.about-us');
})->name('about-us');

Route::get('/contact-us', function(){
    return view('home.contact');
})->name('contact-us');

/** Frontend Routes closes */

Auth::routes();
Route::get('/userprofile', 'UserController@compUser')->name('compuser');
Route::get('/userprofileedit', 'UserController@compUserEdit')->name('compuseredit');
Route::get('/userprofiledel', 'UserController@compUserDel')->name('compuserdel');
Route::get('/register',function(){
    return view('home.register');
})->name('register');

Route::post('/register','UserController@registerUser')->name('register-user');
Route::get('/active/{token}','UserController@activateUser')->name('activate-user');

// Route::get('/register',function(){
//     return redirect()->route('login');
// });


/** Backend Routes */
Route::group(['middleware'=>'auth'],  function(){
    Route::group(['prefix'=>'admin', 'middleware' => 'admin'], function(){
        Route::get('/', 'HomeController@admin')->name('admin');
        Route::resource('company' ,'CompanyController');
        Route::resource('user' ,'UserController');
        Route::resource('banner' ,'BannerController');

        Route::get('/profile','UserController@adminProfile')->name('admin-profile');
        Route::put('/profile/{id}', 'UserController@updateAdmin')->name('admin-update');
        

    });


    Route::group(['prefix'=>'company', 'middleware' => 'company'], function(){
        Route::get('/', 'HomeController@company')->name('company');
        Route::resource('employee' ,'EmployeeController');
    });


    Route::group(['prefix'=>'user', 'middleware' => 'user'], function(){
        Route::get('/', 'HomeController@user')->name('user');
        Route::resource('profileuser' ,'UserFrontController');
    });

});

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role','status','skills','address', 'activation_code'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getRules(){
        return [
            'name' => 'required|string',
            'address' => 'nullable|string',
            'skills' => 'nullable|string',
            'role' => 'required|in:admin,company,user',
            'status' => 'required|in:active,inactive',
            'password' => 'nullable|string|confirmed|min:8|max:16'
        ];
    }

    public function getRegisterRules(){
        return [
            'name' => 'required|string',
            'email' => 'required|email|unique:users,email',
            'address' => 'required|string',
            'skills' => 'nullable|string',
            'role' => 'required|in:company,user',
            'password' => 'required|string|confirmed|min:8|max:16'
        ];
    }

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Mail\ActivateUser;
use App\User;
use Illuminate\Http\Request;
use Mail;

use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    protected $user = null;

    public function __construct(User $user)
    {
        $this->user = $user;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->user = $this->user->where('id', '!=', request()->user()->id)->get();
        return view('admin.user.index')
            ->with('user_data', $this->user);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.form');
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules =$this->user->getRules();
        $request->validate($rules);

        //dd($request);
        $data=$request->all();
        $data['password']=Hash::make($request->password);
        $this->user=$this->user->fill($data);
        $success=$this->user->save();
        if($success){
            $request->session()->flash('success','User added successfully');
        }else{
            $request->session()->flash('error','User not added at this time');
        }
        return redirect()->route('user.index');
    }

    public function registerUser(Request $request){
        $rules = $this->user->getRegisterRules();
        $request->validate($rules);

        $data = $request->all();
        $data['password'] = Hash::make($data['password']);
        $data['status'] = 'inactive';
        $activation_code = \Str::random(100);
        $data['activation_code'] = $activation_code;

        $this->user->fill($data);
        $success = $this->user->save();

        Mail::to($data['email'])->send(new ActivateUser($activation_code));

        return redirect()->route('login');

    }

    public function activateUser($token){
        $this->user = $this->user->where('activation_code', $token)->first();

        // time, reclick

        if(!$this->user){
            request()->session()->flash('error','Invalid token.');
            return redirect()->route('register');
        } else {
            $data = array(
                'activation_code' => null,
                'status' => 'active'
            );
            $this->user->fill($data);
            $this->user->save();
            return redirect()->route('login');
        }
    }

    public function compUser(){
        $this->user = $this->user->where('role', 'User')->get();
        return view('company.user.index')
            ->with('user_data', $this->user);
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->user =$this->user->find($id);
        if(!$this->user){
            request()->session()->flash('error','User not found');
            return redirect()->route('user.index');
        }
        return view('admin.user.form')->with('user_data',$this->user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules =$this->user->getRules('update');
        $request->validate($rules);
        //dd($request);
        $data =$request->all();
        if($request->change_password){
            $data['password']= Hash::make($data['password']);
        }else{
            unset($data['password']);
        }
        $this->user= $this->user->find($id);
        $this->user->fill($data);
        $success =$this->user->save();
        if($success){
            $request->session()->flash('success','User updated successfully');
        }else{
            $request->session()->flash('error',' Error while updating user ');
        }
        return redirect()->route('user.index');

    }

    public function updateAdmin(Request $request, $id){
        $request->request->add(['role' => 'admin']);
        $request->request->add(['status' => 'active']);
        $rules = $this->user->getRules();
        $request->validate($rules);

        $data = $request->all();
        if($request->change_password) {
            $data['password'] = Hash::make($data['password']);
        } else {
            unset($data['password']);
        }

        $this->user = $this->user->find($id);
        $this->user->fill($data);
        $success = $this->user->save();
        if($success){
            $request->session()->flash('success', 'User information updated successfully.');
        } else {
            $request->session()->flash('error', 'Problem while updating user.');
        }
        return redirect()->route('user.index');

    }

    public function adminProfile(){
        $this->user = $this->user->find(request()->user()->id);
        if(!$this->user){
            request()->session()->flash('error','User not found');
            return redirect()->route('user.index');
        }

        return view('admin.user.admin-form')->with('user_data', $this->user);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->user = $this->user->find($id);
        if(!$this->user){
            request()->session()->flash('error','User not found');
            return redirect()->route('user.index');
        }

        $del = $this->user->delete();
        if($del){
            request()->session()->flash('success','User deleted successfully.');
         } else {
            request()->session()->flash('error','Problem while deleting user.');
        }
        return redirect()->route('user.index');
    }
}

resources/views/admin/user/admin-form.blade.php
@extends('layouts.admin-dashboard')

@section('scripts')
<script>
    $('#change_password').change(function() {
        var checked = $('#change_password').prop('checked');
        if (checked) {
            $('#password').attr('required');
            $('#password_confirm').attr('required');
            $('#change_password_div').removeClass('d-none');
        } else {
            $('#password').removeAttr('required');
            $('#password_confirm').removeAttr('required');
            $('#change_password_div').addClass('d-none');
        }
    });
</script>
@endsection
@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Admin {{ isset($user_data) ? 'update' : 'add'}} </h1>
    <div class="row">

        <div class="col-12">
            {{Form::open(['url'=>route('admin-update',$user_data->id),'class'=>'form', 'enctype'=>'multipart/form-data'])  }}
            @method('PUT')




            <div class="form-group row">
                {{ Form::label('name', 'Name: ',['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                    {{Form::text('name', @$user_data->name ,['class'=>'form-control','id'=>'name']) }}
                    @if($errors->has('name'))
                    <span class="alert-danger">{{ $errors->first('name') }}</span>
                    @endif
                </div>
            </div>

            

            <div class="form-group row">
                {{ Form::label('change_password', 'Change password (optional):  ',['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                    {{Form::checkbox('change_password',1,false,['id'=>'change_password']) }} Yes
                    @if($errors->has('change_password'))
                    <span class="alert-danger">{{ $errors->first('change_password') }}</span>
                    @endif
                </div>
            </div>


            <div class="d-none" id="change_password_div">

                <div class="form-group row">
                    {{ Form::label('password', 'Password: ',['class'=>'col-sm-3']) }}
                    <div class="col-sm-9">
                        {{Form::password('password',['id'=>'password','class'=>'form-control']) }}
                        @if($errors->has('password'))
                        <span class="alert-danger">{{ $errors->first('password') }}</span>
                        @endif
                    </div>
                </div>

                <div class="form-group row">
                    {{ Form::label('confirm_password', 'Reenter password: ',['class'=>'col-sm-3']) }}
                    <div class="col-sm-9">
                        {{Form::password('password_confirmation',['id'=>'confirm_password','class'=>'form-control']) }}
                        @if($errors->has('confirm_password'))
                        <span class="alert-danger">{{ $errors->first('confirm_password') }}</span>
                        @endif
                    </div>
                </div>

            </div>


            <div class="form-group row">
                {{ Form::label('', '',['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                    {{Form::button('<i class ="fas fa-plane"></i> Submit',['class'=>'btn btn-success','id'=>'submit','type'=>'submit']) }}
                    {{Form::button('<i class ="fas fa-trash"></i> Cancel',['class'=>'btn btn-danger','id'=>'cancel','type'=>'reset']) }}

                </div>
            </div>


            {{Form::close()}}

        </div>
        @endsection

resources/views/admin/user/form.blade.php
@extends('layouts.admin-dashboard')

@section('scripts')
<script>
    $('#change_password').change(function() {
        var checked = $('#change_password').prop('checked');
        if (checked) {
            $('#password').attr('required');
            $('#password_confirm').attr('required');
            $('#change_password_div').removeClass('d-none');
        } else {
            $('#password').removeAttr('required');
            $('#password_confirm').removeAttr('required');
            $('#change_password_div').addClass('d-none');
        }
    });
</script>
@endsection
@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">User {{ isset($user_data) ? 'update' : 'add'}} </h1>
    <div class="row">

        <div class="col-12">
        @if(isset($user_data))
                       {{Form::open(['url'=>route('user.update',$user_data->id),'class'=>'form', 'enctype'=>'multipart/form-data'])  }}
                            @method('PUT')

                        @else
                        {{Form::open(['url'=>route('user.store'),'class'=>'form', 'enctype'=>'multipart/form-data'])  }}

                        @endif


                        <div class="form-group row">
                            {{ Form::label('name', 'Name: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::text('name', @$user_data->name ,['class'=>'form-control','id'=>'name']) }}
                                @if($errors->has('name'))
                                <span class="alert-danger">{{ $errors->first('name') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row" style="display: {{ isset($user_data) ? 'd-none' : 'd-block' }}">
                            {{ Form::label('email', 'Email: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::text('email', @$user_data->email ,['class'=>'form-control','id'=>'email','rows'=>5,'style'=>'resize:none']) }}
                                @if($errors->has('email'))
                                <span class="alert-danger">{{ $errors->first('email') }}</span>
                                @endif
                            </div>
                        </div>



                        

                        <div class="form-group row" style=" isset($user_data) ? 'd-none' : 'd-block'  ">
                            {{ Form::label('change_password', 'Change password (optional): ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::checkbox('change_password',1,false,['id'=>'change_password']) }} Yes
                                @if($errors->has('change_password'))
                                <span class="alert-danger">{{ $errors->first('change_password') }}</span>
                                @endif
                            </div>
                        </div>
                       


                        <div class=" {{ isset($user_data)?'d-none':''}}" id="change_password_div">

                        <div class="form-group row" style=" isset($user_data) ? 'd-none' : 'd-block'  ">
                            {{ Form::label('password', 'Password: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::password('password',['id'=>'password','class'=>'form-control']) }}
                                @if($errors->has('password'))
                                <span class="alert-danger">{{ $errors->first('password') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row" style=" isset($user_data) ? 'd-none' : 'd-block'  ">
                            {{ Form::label('confirm_password', 'Reenter password: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::password('password_confirmation',['id'=>'confirm_password','class'=>'form-control']) }}
                                @if($errors->has('confirm_password'))
                                <span class="alert-danger">{{ $errors->first('confirm_password') }}</span>
                                @endif
                            </div>
                        </div>

                        </div>


                        <div class="form-group row">
                            {{ Form::label('role', 'Role: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::select('role',['user'=>'User'],@$user_data->role ,['class'=>'form-control','id'=>'role']) }}
                                @if($errors->has('role'))
                                <span class="alert-danger">{{ $errors->first('role') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ Form::label('status', 'Status: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::select('status',['active'=>"Active",'inactive'=>'Inactive'],@$user_data->status ,['class'=>'form-control','id'=>'status']) }}
                                @if($errors->has('status'))
                                <span class="alert-danger">{{ $errors->first('status') }}</span>
                                @endif
                            </div>
                        </div>



                        <div class="form-group row">
                            {{ Form::label('', '',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::button('<i class ="fas fa-plane"></i> Submit',['class'=>'btn btn-success','id'=>'submit','type'=>'submit']) }}
                                {{Form::button('<i class ="fas fa-trash"></i> Cancel',['class'=>'btn btn-danger','id'=>'cancel','type'=>'reset']) }}

                            </div>
                        </div>


                        {{Form::close()}}
</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin-dashboard')

@section('title')
User List || Admin, EduTraining
@endsection
@section('datataleslinks')
<link rel="stylesheet" href="{{ asset('assets/admin/css/jquery.dataTables.min.css') }}">
@endsection
@section('datatablesscripts')
<script src="{{ asset('assets/admin/js/jquery.dataTables.min.js') }}"></script>
<script>
    $('.table').dataTable();
</script>
@endsection


@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">User List
    </h1>
    @include('admin.section.notification')
    <table class="table">
        <thead>
            <th>S.N </th>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Status</th>
            <th>Action</th>
        </thead>
        <tbody>
        @if($user_data)
            @foreach($user_data as $key=>$value)
            <tr>
                <td> {{ $key+1 }}</td>
                <td>{{ $value->name }}</td>
                <td>{{ $value->email }}</td>
                <td>{{ ucfirst($value->role)}}</td>
                <td>{{ ucfirst($value->status) }}</td>

                <td> <a href="{{ route('user.edit', $value->id) }}" style="border-radius: 50%" class="btn btn-success">
                        <i class="fas fa-pencil-alt"></i>
                    </a>

                    <form onsubmit="return confirm('Are you sure you want to delete this user?')" action="{{ route('user.destroy', $value->id) }}" method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" style="border-radius: 50%">
                            <i class="fas fa-trash"></i>
                        </button>
                    </form>
                </td>
            </tr>
            @endforeach
            @endif
        </tbody>
    </table>

</div>
@endsection